// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjqwjdjxchhcmwfqcpnk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qcXdqZGp4Y2hoY213ZnFjcG5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNDk1MjcsImV4cCI6MjA3MTYyNTUyN30.MmINQ3y6hZLIlup8rv8B_yluccUc4fdCrBsE91_It18";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});